name: "Bug Report"
description: "If something isn't working as expected."
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: Thank you for submitting a bug report! Please fill out this form.
  - type: checkboxes
    id: input1
    attributes:
      label: "💻"
      options:
        - label: Would you like to work on a fix?
  - type: dropdown
    attributes:
      label: Package name
      options:
        - components-override
    validations:
      required: true
  - type: textarea
    attributes:
      label: Input code
      description: |
        You must write here the minimal input code necessary to reproduce the bug.
      placeholder: |
        ... source code
  - type: textarea
    attributes:
      label: Current and expected behavior
      description: A clear and concise description of what behavior is now and what you expect from it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible solution
      description: If you have suggestions on a fix for the bug.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
